package handlers

import (
	"fmt"

	"x-downloader/config"
	"x-downloader/models"
	"x-downloader/services"
	"x-downloader/utils"

	"github.com/gofiber/fiber/v2"
)

type SubtitleInfo struct {
	Lang          string `json:"lang"`
	URL           string `json:"url"`
	AutoGenerated bool   `json:"autoGenerated"`
}

type InfoResponse struct {
	Title     string         `json:"title"`
	Caption   string         `json:"caption,omitempty"`
	Author    string         `json:"author,omitempty"`
	Duration  float64        `json:"duration"`
	Thumbnail string         `json:"thumbnail,omitempty"`
	VideoURL  string         `json:"videoUrl,omitempty"`
	AudioURL  string         `json:"audioUrl,omitempty"`
	Subtitles []SubtitleInfo `json:"subtitles"`
}

// HandleInfo handles GET /api/info?url=<post_url> — returns post metadata for preview without downloading
func HandleInfo(c *fiber.Ctx) error {
	hubToken := c.Get("X-Hub-Token")
	if hubToken != config.HubToken {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"error": "Unauthorized",
		})
	}

	reqURL := c.Query("url")
	if reqURL == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "URL is required",
		})
	}

	if !utils.IsXURL(reqURL) {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Invalid X/Twitter URL",
		})
	}

	postData, err := services.Extract(reqURL)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": fmt.Sprintf("Failed to extract post info: %v", err),
		})
	}

	title := postData.Title
	if title == "" {
		title = postData.Caption
	}
	if len(title) > 100 {
		title = title[:100]
	}
	if title == "" {
		title = "X " + postData.ID
	}

	var duration float64
	if postData.VideoDuration != nil {
		duration = *postData.VideoDuration
	}

	thumbnail := postData.GetImageURL()
	if thumbnail != "" {
		thumbnail = utils.GenerateMediaProxyURL(thumbnail)
	}

	videoURL := postData.GetVideoProgressiveURL()
	if videoURL == "" {
		videoURL = postData.GetVideoURL()
	}
	if videoURL != "" {
		videoURL = utils.GenerateMediaProxyURL(videoURL)
	}

	audioURL := postData.GetAudioURL()
	if audioURL != "" {
		audioURL = utils.GenerateMediaProxyURL(audioURL)
	}

	return c.JSON(InfoResponse{
		Title:     title,
		Caption:   postData.Caption,
		Author:    postData.OwnerUsername,
		Duration:  duration,
		Thumbnail: thumbnail,
		VideoURL:  videoURL,
		AudioURL:  audioURL,
		Subtitles: mapSubtitles(postData.Subtitles),
	})
}

func mapSubtitles(subs []models.Subtitle) []SubtitleInfo {
	result := make([]SubtitleInfo, 0, len(subs))
	for _, s := range subs {
		subURL := s.URL
		if subURL != "" {
			subURL = utils.GenerateMediaProxyURL(subURL)
		}
		result = append(result, SubtitleInfo{
			Lang:          s.Lang,
			URL:           subURL,
			AutoGenerated: s.AutoGenerated,
		})
	}
	return result
}
