package config

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"
)

type ConfigFetcher struct {
	hubURL   string
	serverIP string
}

func NewConfigFetcher(hubURL string) *ConfigFetcher {
	return &ConfigFetcher{
		hubURL:   hubURL,
		serverIP: detectServerIP(),
	}
}

// detectServerIP detects public IP
func detectServerIP() string {
	// Provider list to try
	providers := []string{
		"https://api.ipify.org",
		"https://checkip.amazonaws.com",
		"https://ifconfig.me/ip", // /ip path for plain text
	}

	client := &http.Client{Timeout: 5 * time.Second}

	for _, url := range providers {
		req, _ := http.NewRequest("GET", url, nil)
		req.Header.Set("User-Agent", "curl/7.68.0") // Pretend to be curl

		resp, err := client.Do(req)
		if err == nil {
			defer resp.Body.Close()
			if resp.StatusCode == 200 {
				var ip string
				fmt.Fscanf(resp.Body, "%s", &ip)
				ip = strings.TrimSpace(ip)
				// Basic validation: should not start with < (HTML)
				if ip != "" && !strings.HasPrefix(ip, "<") {
					return ip
				}
			}
		}
	}

	// Fallback to local IP via hostname command
	cmd := exec.Command("hostname", "-I")
	output, _ := cmd.Output()
	// Get first IP
	ips := strings.Fields(string(output))
	if len(ips) > 0 {
		return ips[0]
	}

	// Last resort: simple hostname
	return "127.0.0.1"
}

// RegisterWithHub registers VPS with auto-generated config
func (f *ConfigFetcher) RegisterWithHub() (map[string]interface{}, error) {
	// Generate config
	config := GenerateConfig(f.serverIP)

	// Register with Hub
	url := fmt.Sprintf("%s/api/server-config/register", f.hubURL)
	body, _ := json.Marshal(config)

	req, _ := http.NewRequest("POST", url, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Real-IP", f.serverIP)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to connect to hub: %w", err)
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, err
	}

	return result, nil
}

// FetchConfig fetches latest config from Hub
func (f *ConfigFetcher) FetchConfig() (map[string]interface{}, error) {
	url := fmt.Sprintf("%s/api/server-config/%s", f.hubURL, f.serverIP)

	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch config: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == 404 {
		return nil, fmt.Errorf("config not found")
	}

	var config map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&config); err != nil {
		return nil, err
	}

	return config, nil
}

// GenerateEnvFile generates .env file from config
func (f *ConfigFetcher) GenerateEnvFile(config map[string]interface{}, envPath string) error {
	file, err := os.Create(envPath)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintf(file, "# Generated by VPS Agent at %s\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(file, "# Hub: %s\n", f.hubURL)
	fmt.Fprintf(file, "# Server IP: %s\n\n", f.serverIP)

	// Core Identity
	fmt.Fprintf(file, "# === Core Identity ===\n")
	fmt.Fprintf(file, "SERVER_IP=%v\n", config["server_ip"])
	fmt.Fprintf(file, "SERVER_NAME=%v\n", config["name"])

	// Domain Structure
	fmt.Fprintf(file, "BASE_DOMAIN=ytconvert.org\n")
	fmt.Fprintf(file, "DOWNLOAD_SUBDOMAIN=%v\n", config["subdomain"])
	fmt.Fprintf(file, "EXTRACTOR_SUBDOMAIN=ext-%v\n", config["subdomain"])

	fmt.Fprintf(file, "EMAIL=%v\n", config["email"])
	fmt.Fprintf(file, "PORT=%v\n\n", config["port"])

	// Proxy Credentials
	fmt.Fprintf(file, "# === Proxy Credentials ===\n")
	fmt.Fprintf(file, "WARP_USER=%v\n", config["warp_user"])
	fmt.Fprintf(file, "WARP_PASS=%v\n", config["warp_pass"])
	fmt.Fprintf(file, "DIRECT_USER=%v\n", config["direct_user"])
	fmt.Fprintf(file, "DIRECT_PASS=%v\n\n", config["direct_pass"])

	// Storage & Download
	fmt.Fprintf(file, "# === Storage & Download ===\n")
	fmt.Fprintf(file, "STORAGE_DIR=%v\n", config["storage_dir"])
	fmt.Fprintf(file, "DOWNLOAD_THREADS=%v\n", config["download_threads"])
	fmt.Fprintf(file, "CHUNK_SIZE=%v\n", config["chunk_size"])
	fmt.Fprintf(file, "MAX_RETRIES=%v\n", config["max_retries"])
	fmt.Fprintf(file, "RETRY_DELAY_MS=%v\n", config["retry_delay_ms"])
	fmt.Fprintf(file, "CHUNK_TIMEOUT_S=%v\n\n", config["chunk_timeout_s"])

	// Extract API
	fmt.Fprintf(file, "# === Extract API ===\n")
	fmt.Fprintf(file, "EXTRACT_API_TIMEOUT=%v\n\n", config["extract_api_timeout"])

	// Cleanup
	fmt.Fprintf(file, "# === Cleanup ===\n")
	fmt.Fprintf(file, "CLEANUP_INTERVAL=%v\n", config["cleanup_interval"])
	fmt.Fprintf(file, "MAX_JOB_AGE_MIN=%v\n", config["max_job_age_min"])
	fmt.Fprintf(file, "CLEANUP_BATCH_SIZE=%v\n\n", config["cleanup_batch_size"])

	// Security
	fmt.Fprintf(file, "# === Security ===\n")
	fmt.Fprintf(file, "SIGNED_URL_SECRET=%v\n", config["signed_url_secret"])
	fmt.Fprintf(file, "SIGNED_URL_EXPIRATION_MIN=%v\n\n", config["signed_url_expiration_min"])

	// Limits
	fmt.Fprintf(file, "# === Limits ===\n")
	fmt.Fprintf(file, "MAX_TRIM_DURATION_MIN=%v\n", config["max_trim_duration_min"])
	fmt.Fprintf(file, "MAX_FILE_SIZE_GB=%v\n\n", config["max_file_size_gb"])

	// Feature Flags
	fmt.Fprintf(file, "# === Feature Flags ===\n")
	fmt.Fprintf(file, "ENABLE_MERGE=%v\n", config["enable_merge"])
	fmt.Fprintf(file, "ENABLE_TRIM=%v\n", config["enable_trim"])
	fmt.Fprintf(file, "ENABLE_REENCODE=%v\n\n", config["enable_reencode"])

	// Tier Config
	fmt.Fprintf(file, "# === Tier Config ===\n")
	fmt.Fprintf(file, "TIER_CONFIG=%v\n", config["tier_config"])

	log.Printf("[Agent] Generated .env file: %s", envPath)
	return nil
}

func (f *ConfigFetcher) GetServerIP() string {
	return f.serverIP
}
