server:
  port: 8100

spring:
  application:
    name: youtube-api

logging:
  level:
    root: OFF
    com.youtube.api: OFF
    org.schabi.newpipe: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
