package handlers

import (
	"fmt"
	"tik-downloader/services"
	"tik-downloader/utils"

	"github.com/gofiber/fiber/v2"
)

type SubtitleInfo struct {
	Lang          string `json:"lang"`
	URL           string `json:"url"`
	AutoGenerated bool   `json:"autoGenerated"`
}

type InfoResponse struct {
	Title     string         `json:"title"`
	Caption   string         `json:"caption,omitempty"`
	Author    string         `json:"author,omitempty"`
	Duration  float64        `json:"duration"`
	Thumbnail string         `json:"thumbnail,omitempty"`
	VideoURL  string         `json:"videoUrl,omitempty"`
	AudioURL  string         `json:"audioUrl,omitempty"`
	Subtitles []SubtitleInfo `json:"subtitles"`
}

// HandleInfo handles GET /api/info?url=<video_url> — returns video metadata for preview without downloading
func HandleInfo(c *fiber.Ctx) error {

	reqURL := c.Query("url")
	if reqURL == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "URL is required",
		})
	}

	videoID, err := utils.ExtractVideoID(reqURL)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": fmt.Sprintf("Invalid TikTok URL: %v", err),
		})
	}

	videoData, err := services.Extract(videoID)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": fmt.Sprintf("Failed to extract video info: %v", err),
		})
	}

	title := videoData.Data.Desc
	if title == "" {
		title = "TikTok Video " + videoID
	}

	// Wrap media URLs with signed proxy
	videoURL := videoData.Data.GetDownloads()
	if videoURL != "" {
		videoURL = utils.GenerateMediaProxyURL(videoURL)
	}
	audioURL := videoData.Data.MusicURL
	if audioURL != "" {
		audioURL = utils.GenerateMediaProxyURL(audioURL)
	}
	thumbnail := videoData.Data.StaticCover
	if thumbnail != "" {
		thumbnail = utils.GenerateMediaProxyURL(thumbnail)
	}

	return c.JSON(InfoResponse{
		Title:     title,
		Caption:   videoData.Data.Desc,
		Author:    videoData.Data.Nickname,
		Duration:  services.ParseDuration(videoData.Data.Duration),
		Thumbnail: thumbnail,
		VideoURL:  videoURL,
		AudioURL:  audioURL,
		Subtitles: []SubtitleInfo{},
	})
}
