package com.youtube.api.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SubtitleDTO {
    private String url;
    private String languageCode;
    private String languageName;
    private String format;
    private Boolean autoGenerated;
}
