package handlers

import (
	"yt-downloader-go/services"
	"yt-downloader-go/utils"

	"github.com/gofiber/fiber/v2"
)

type SubtitleInfo struct {
	Lang          string `json:"lang"`
	URL           string `json:"url"`
	OriginalURL   string `json:"originalUrl,omitempty"`
	AutoGenerated bool   `json:"autoGenerated"`
}

type InfoResponse struct {
	Title             string         `json:"title"`
	Caption           string         `json:"caption,omitempty"`
	Author            string         `json:"author,omitempty"`
	Duration          float64        `json:"duration"`
	Thumbnail         string         `json:"thumbnail,omitempty"`
	OriginalThumbnail string         `json:"originalThumbnail,omitempty"`
	VideoURL          string         `json:"videoUrl,omitempty"`
	OriginalVideoURL  string         `json:"originalVideoUrl,omitempty"`
	AudioURL          string         `json:"audioUrl,omitempty"`
	OriginalAudioURL  string         `json:"originalAudioUrl,omitempty"`
	Subtitles         []SubtitleInfo `json:"subtitles"`
}

// HandleInfo handles GET /api/info?url=<video_url> — returns video metadata for preview without downloading
func HandleInfo(c *fiber.Ctx) error {
	const hubToken = "1234567890987654321234567890987654321"
	token := c.Get("X-Hub-Token")
	if token != hubToken {
		return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
			"error": "Unauthorized: Invalid or missing hub token",
		})
	}

	reqURL := c.Query("url")
	if reqURL == "" {
		return utils.BadRequest(c, utils.ErrValidationError, "URL is required")
	}

	videoID, err := utils.ExtractVideoID(reqURL)
	if err != nil {
		return utils.BadRequest(c, utils.ErrInvalidURL, err.Error())
	}

	extractData, err := services.Extract(videoID, false)
	if err != nil {
		return utils.InternalError(c, "Failed to fetch video metadata")
	}

	// Pick best video URL for preview (highest resolution)
	var videoURL string
	var bestHeight int
	for _, s := range extractData.VideoStreams {
		if s.Height > bestHeight {
			bestHeight = s.Height
			videoURL = s.URL
		}
	}

	// Pick best audio URL for preview (highest bitrate)
	var audioURL string
	var bestBitrate float64
	for _, s := range extractData.AudioStreams {
		if s.Bitrate > bestBitrate {
			bestBitrate = s.Bitrate
			audioURL = s.URL
		}
	}

	// Keep originals, wrap with signed proxy as fallback
	originalVideoURL := videoURL
	originalAudioURL := audioURL
	originalThumbnail := extractData.ThumbnailURL

	if videoURL != "" {
		videoURL = utils.GenerateMediaProxyURL(videoURL)
	}
	if audioURL != "" {
		audioURL = utils.GenerateMediaProxyURL(audioURL)
	}
	thumbnail := originalThumbnail
	if thumbnail != "" {
		thumbnail = utils.GenerateMediaProxyURL(thumbnail)
	}

	subtitles := make([]SubtitleInfo, 0, len(extractData.Subtitles))
	for _, s := range extractData.Subtitles {
		if s.URL == "" {
			continue
		}
		subtitles = append(subtitles, SubtitleInfo{
			Lang:          s.Lang,
			URL:           utils.GenerateCaptionURL(s.URL, s.Lang, extractData.Duration),
			OriginalURL:   s.URL,
			AutoGenerated: s.AutoGenerated,
		})
	}

	return c.JSON(InfoResponse{
		Title:             extractData.Title,
		Author:            extractData.Author,
		Duration:          extractData.Duration,
		Thumbnail:         thumbnail,
		OriginalThumbnail: originalThumbnail,
		VideoURL:          videoURL,
		OriginalVideoURL:  originalVideoURL,
		AudioURL:          audioURL,
		OriginalAudioURL:  originalAudioURL,
		Subtitles:         subtitles,
	})
}
