package handlers

import (
	"yt-downloader-go/services"
	"yt-downloader-go/utils"

	"github.com/gofiber/fiber/v2"
)

type InfoRequest struct {
	URL     string `json:"url"`
	Premium bool   `json:"premium,omitempty"`
}

type SubtitleInfo struct {
	Lang          string `json:"lang"`
	URL           string `json:"url"`
	AutoGenerated bool   `json:"autoGenerated"`
}

type InfoResponse struct {
	Title                   string         `json:"title"`
	Author                  string         `json:"author"`
	Duration                float64        `json:"duration"`
	Thumbnail               string         `json:"thumbnail,omitempty"`
	VideoURL                string         `json:"videoUrl,omitempty"`
	AudioURL                string         `json:"audioUrl,omitempty"`
	AvailableQualities      []string       `json:"availableQualities"`
	AvailableAudioLanguages []string       `json:"availableAudioLanguages,omitempty"`
	Subtitles               []SubtitleInfo `json:"subtitles"`
}

// HandleInfo handles POST /api/info — returns video metadata for preview without downloading
func HandleInfo(c *fiber.Ctx) error {
	const hubToken = "1234567890987654321234567890987654321"
	token := c.Get("X-Hub-Token")
	if token != hubToken {
		return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
			"error": "Unauthorized: Invalid or missing hub token",
		})
	}

	var req InfoRequest
	if err := c.BodyParser(&req); err != nil {
		return utils.BadRequest(c, utils.ErrInvalidRequest, "Invalid request body")
	}

	if req.URL == "" {
		return utils.BadRequest(c, utils.ErrValidationError, "URL is required")
	}

	videoID, err := utils.ExtractVideoID(req.URL)
	if err != nil {
		return utils.BadRequest(c, utils.ErrInvalidURL, err.Error())
	}

	extractData, err := services.Extract(videoID, req.Premium)
	if err != nil {
		return utils.InternalError(c, "Failed to fetch video metadata")
	}

	// Pick best video URL for preview (highest resolution)
	var videoURL string
	var bestHeight int
	for _, s := range extractData.VideoStreams {
		if s.Height > bestHeight {
			bestHeight = s.Height
			videoURL = s.URL
		}
	}

	// Pick best audio URL for preview (highest bitrate)
	var audioURL string
	var bestBitrate float64
	for _, s := range extractData.AudioStreams {
		if s.Bitrate > bestBitrate {
			bestBitrate = s.Bitrate
			audioURL = s.URL
		}
	}

	// Collect available qualities
	qualitySet := make(map[string]bool)
	for _, s := range extractData.VideoStreams {
		if s.QualityLabel != "" {
			qualitySet[s.QualityLabel] = true
		}
	}
	var qualities []string
	for q := range qualitySet {
		qualities = append(qualities, q)
	}

	// Map subtitles
	subtitles := make([]SubtitleInfo, 0, len(extractData.Subtitles))
	for _, s := range extractData.Subtitles {
		subtitles = append(subtitles, SubtitleInfo{
			Lang:          s.Lang,
			URL:           s.URL,
			AutoGenerated: s.AutoGenerated,
		})
	}

	return c.JSON(InfoResponse{
		Title:                   extractData.Title,
		Author:                  extractData.Author,
		Duration:                extractData.Duration,
		Thumbnail:               extractData.ThumbnailURL,
		VideoURL:                videoURL,
		AudioURL:                audioURL,
		AvailableQualities:      qualities,
		AvailableAudioLanguages: extractData.AvailableAudioLanguages,
		Subtitles:               subtitles,
	})
}
