package handlers

import (
	"context"
	"fmt"
	"path/filepath"
	"time"
	"yt-downloader-go/config"
	"yt-downloader-go/models"
	"yt-downloader-go/services"
	"yt-downloader-go/utils"

	"github.com/gofiber/fiber/v2"
)

type PrepareResponse struct {
	StatusURL string         `json:"statusUrl"`
	Title     string         `json:"title"`
	Author    string         `json:"author,omitempty"`
	Duration  float64        `json:"duration"`
	Thumbnail string         `json:"thumbnail,omitempty"`
	VideoURL  string         `json:"videoUrl,omitempty"`
	AudioURL  string         `json:"audioUrl,omitempty"`
	Subtitles []SubtitleInfo `json:"subtitles"`
}

type PrepareStatusResponse struct {
	Status        string             `json:"status"`
	Progress      int                `json:"progress"`
	VideoURL      string             `json:"videoUrl,omitempty"`
	AudioURL      string             `json:"audioUrl,omitempty"`
	VideoProgress *PrepareFileStatus `json:"videoProgress"`
	AudioProgress *PrepareFileStatus `json:"audioProgress"`
	Error         string             `json:"error,omitempty"`
}

type PrepareFileStatus struct {
	Progress int    `json:"progress"`
	URL      string `json:"url,omitempty"`
}

// HandlePrepare handles POST /api/prepare — extracts metadata, starts background download of video+audio
func HandlePrepare(c *fiber.Ctx) error {
	const hubToken = "1234567890987654321234567890987654321"
	token := c.Get("X-Hub-Token")
	if token != hubToken {
		return c.Status(fiber.StatusForbidden).JSON(fiber.Map{
			"error": "Unauthorized: Invalid or missing hub token",
		})
	}

	var req models.DownloadRequest
	if err := c.BodyParser(&req); err != nil {
		return utils.BadRequest(c, utils.ErrInvalidRequest, "Invalid request body")
	}

	if req.URL == "" {
		return utils.BadRequest(c, utils.ErrValidationError, "URL is required")
	}

	videoID, err := utils.ExtractVideoID(req.URL)
	if err != nil {
		return utils.BadRequest(c, utils.ErrInvalidURL, err.Error())
	}

	extractData, err := services.Extract(videoID, req.Premium)
	if err != nil {
		return utils.InternalError(c, "Failed to fetch video metadata")
	}

	// Pick best H.264 video (widest compatibility)
	osType := req.OS
	if osType == "" {
		osType = "windows"
	}
	videoSelection := services.SelectVideo(extractData, "1080p", osType, "mp4")
	if videoSelection.Stream == nil {
		return utils.NotFound(c, utils.ErrVideoNotFound, "No compatible video stream found")
	}

	audioSelection := services.SelectAudio(extractData, "", osType, "mp4")
	if audioSelection.Stream == nil {
		return utils.NotFound(c, utils.ErrAudioNotFound, "No compatible audio stream found")
	}

	// Generate job ID
	jobID := generateID()
	if err := utils.CreateJobDir(jobID); err != nil {
		return utils.InternalError(c, "Failed to create job directory")
	}

	// Determine file extensions
	videoExt := services.GetExtension(videoSelection.Stream)
	audioExt := services.GetExtension(audioSelection.Stream)

	// Save prepare meta
	meta := &models.PrepareMeta{
		ID:        jobID,
		Status:    models.StatusPending,
		CreatedAt: time.Now().UnixMilli(),
		VideoID:   videoID,
		Title:     extractData.Title,
		Author:    extractData.Author,
		Duration:  extractData.Duration,
		VideoFile: "video." + videoExt,
		AudioFile: "audio." + audioExt,
		VideoSize: videoSelection.Stream.ContentLength,
		AudioSize: audioSelection.Stream.ContentLength,
	}

	if err := utils.WritePrepareMeta(jobID, meta); err != nil {
		utils.DeleteJobDir(jobID)
		return utils.InternalError(c, "Failed to save job metadata")
	}

	// Start background download
	threads := config.GetDownloadThreads(req.CTier)
	go processPrepareJob(jobID, meta, videoSelection, audioSelection.Stream, threads, req.Premium)

	// Build preview response (same as info)
	originalVideoURL := videoSelection.Stream.URL
	originalAudioURL := audioSelection.Stream.URL

	proxyVideoURL := utils.GenerateMediaProxyURL(originalVideoURL)
	proxyAudioURL := utils.GenerateMediaProxyURL(originalAudioURL)

	thumbnail := extractData.ThumbnailURL
	if thumbnail != "" {
		thumbnail = utils.GenerateMediaProxyURL(thumbnail)
	}

	subtitles := make([]SubtitleInfo, 0, len(extractData.Subtitles))
	for _, s := range extractData.Subtitles {
		if s.URL == "" {
			continue
		}
		subtitles = append(subtitles, SubtitleInfo{
			Lang:          s.Lang,
			URL:           utils.GenerateCaptionURL(s.URL, s.Lang, extractData.Duration),
			AutoGenerated: s.AutoGenerated,
		})
	}

	return c.Status(fiber.StatusCreated).JSON(PrepareResponse{
		StatusURL: utils.GeneratePrepareStatusURL(jobID),
		Title:     extractData.Title,
		Author:    extractData.Author,
		Duration:  extractData.Duration,
		Thumbnail: thumbnail,
		VideoURL:  proxyVideoURL,
		AudioURL:  proxyAudioURL,
		Subtitles: subtitles,
	})
}

// HandlePrepareStatus handles GET /api/prepare/status/:id
func HandlePrepareStatus(c *fiber.Ctx) error {
	jobID := c.Params("id")
	if !utils.ValidateJobID(jobID) {
		return utils.BadRequest(c, utils.ErrInvalidJobID, "Invalid job ID format")
	}

	token := c.Query("token")
	expiresStr := c.Query("expires")
	if token == "" || expiresStr == "" {
		return utils.Unauthorized(c, "Missing token or expires parameter")
	}

	expires, err := utils.ParseExpires(expiresStr)
	if err != nil {
		return utils.BadRequest(c, utils.ErrInvalidRequest, "Invalid expires format")
	}

	if !utils.ValidatePrepareStatusURL(jobID, token, expires) {
		return utils.Forbidden(c, "Invalid or expired token")
	}

	meta, err := utils.ReadPrepareMeta(jobID)
	if err != nil {
		return utils.NotFound(c, utils.ErrJobNotFound, "Job not found")
	}

	videoProgress, audioProgress := utils.CalculatePrepareProgressSeparate(meta)

	videoStatus := &PrepareFileStatus{Progress: videoProgress}
	audioStatus := &PrepareFileStatus{Progress: audioProgress}

	// Return signed URL as soon as each file is done (progress == 100)
	if videoProgress == 100 {
		videoStatus.URL = utils.GenerateSignedURL(jobID, meta.VideoFile)
	}
	if audioProgress == 100 {
		audioStatus.URL = utils.GenerateSignedURL(jobID, meta.AudioFile)
	}

	overallProgress := int(float64(videoProgress)*0.7 + float64(audioProgress)*0.3)

	response := PrepareStatusResponse{
		Status:        meta.Status,
		Progress:      min(overallProgress, 100),
		VideoProgress: videoStatus,
		AudioProgress: audioStatus,
	}

	if meta.Status == models.StatusCompleted {
		response.Progress = 100
		response.VideoURL = videoStatus.URL
		response.AudioURL = audioStatus.URL
	}

	if meta.Status == models.StatusError {
		response.Error = meta.Error
	}

	return c.JSON(response)
}

func processPrepareJob(jobID string, meta *models.PrepareMeta, videoSelection *models.VideoSelectionResult, audioStream *models.Stream, threads int, premium bool) {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Minute)
	defer cancel()

	jobDir := utils.GetJobDir(jobID)

	defer func() {
		if r := recover(); r != nil {
			utils.UpdatePrepareMetaError(jobID, "Internal error")
		}
	}()

	// Download video and audio in parallel
	errChan := make(chan error, 2)

	go func() {
		videoPath := filepath.Join(jobDir, meta.VideoFile)
		errChan <- services.Download(ctx, makeURLProvider(meta.VideoID, videoSelection.Stream, true, premium), videoPath, videoSelection.Stream.ContentLength, threads)
	}()

	go func() {
		audioPath := filepath.Join(jobDir, meta.AudioFile)
		errChan <- services.Download(ctx, makeURLProvider(meta.VideoID, audioStream, false, premium), audioPath, audioStream.ContentLength, threads)
	}()

	for i := 0; i < 2; i++ {
		if err := <-errChan; err != nil {
			utils.UpdatePrepareMetaError(jobID, "Download failed: "+err.Error())
			return
		}
	}

	utils.UpdatePrepareMetaCompleted(jobID)
	fmt.Printf("[Prepare/%s] Job completed: video=%s audio=%s\n", jobID, meta.VideoFile, meta.AudioFile)
}
